//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CLMSModel", "FK__Admin__PersonId__3C69FB99", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapstoneProj.Model.dbEntity.Person), "Admin", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapstoneProj.Model.dbEntity.Admin), true)]
[assembly: EdmRelationshipAttribute("CLMSModel", "FK__Computer__Labora__44FF419A", "Laboratory", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapstoneProj.Model.dbEntity.Laboratory), "Computer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapstoneProj.Model.dbEntity.Computer), true)]
[assembly: EdmRelationshipAttribute("CLMSModel", "FK__Reservati__Compu__4D94879B", "Computer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapstoneProj.Model.dbEntity.Computer), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapstoneProj.Model.dbEntity.Reservation), true)]
[assembly: EdmRelationshipAttribute("CLMSModel", "FK_Gender", "Gender", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapstoneProj.Model.dbEntity.Gender), "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapstoneProj.Model.dbEntity.Person), true)]
[assembly: EdmRelationshipAttribute("CLMSModel", "FK__Reservati__Labor__4CA06362", "Laboratory", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapstoneProj.Model.dbEntity.Laboratory), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapstoneProj.Model.dbEntity.Reservation), true)]
[assembly: EdmRelationshipAttribute("CLMSModel", "FK__Student__PersonI__403A8C7D", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapstoneProj.Model.dbEntity.Person), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapstoneProj.Model.dbEntity.Student), true)]
[assembly: EdmRelationshipAttribute("CLMSModel", "FK__Student__Program__0E6E26BF", "ProgramCourse", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapstoneProj.Model.dbEntity.ProgramCourse), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapstoneProj.Model.dbEntity.Student), true)]
[assembly: EdmRelationshipAttribute("CLMSModel", "FK__Reservati__Statu__4F7CD00D", "StatusType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapstoneProj.Model.dbEntity.StatusType), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapstoneProj.Model.dbEntity.Reservation), true)]
[assembly: EdmRelationshipAttribute("CLMSModel", "FK__Reservati__Stude__4BAC3F29", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapstoneProj.Model.dbEntity.Student), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapstoneProj.Model.dbEntity.Reservation), true)]

#endregion

namespace CapstoneProj.Model.dbEntity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CLMSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CLMSEntities object using the connection string found in the 'CLMSEntities' section of the application configuration file.
        /// </summary>
        public CLMSEntities() : base("name=CLMSEntities", "CLMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CLMSEntities object.
        /// </summary>
        public CLMSEntities(string connectionString) : base(connectionString, "CLMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CLMSEntities object.
        /// </summary>
        public CLMSEntities(EntityConnection connection) : base(connection, "CLMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Admin> Admins
        {
            get
            {
                if ((_Admins == null))
                {
                    _Admins = base.CreateObjectSet<Admin>("Admins");
                }
                return _Admins;
            }
        }
        private ObjectSet<Admin> _Admins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Computer> Computers
        {
            get
            {
                if ((_Computers == null))
                {
                    _Computers = base.CreateObjectSet<Computer>("Computers");
                }
                return _Computers;
            }
        }
        private ObjectSet<Computer> _Computers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Gender> Genders
        {
            get
            {
                if ((_Genders == null))
                {
                    _Genders = base.CreateObjectSet<Gender>("Genders");
                }
                return _Genders;
            }
        }
        private ObjectSet<Gender> _Genders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Laboratory> Laboratories
        {
            get
            {
                if ((_Laboratories == null))
                {
                    _Laboratories = base.CreateObjectSet<Laboratory>("Laboratories");
                }
                return _Laboratories;
            }
        }
        private ObjectSet<Laboratory> _Laboratories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProgramCourse> ProgramCourses
        {
            get
            {
                if ((_ProgramCourses == null))
                {
                    _ProgramCourses = base.CreateObjectSet<ProgramCourse>("ProgramCourses");
                }
                return _ProgramCourses;
            }
        }
        private ObjectSet<ProgramCourse> _ProgramCourses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reservation> Reservations
        {
            get
            {
                if ((_Reservations == null))
                {
                    _Reservations = base.CreateObjectSet<Reservation>("Reservations");
                }
                return _Reservations;
            }
        }
        private ObjectSet<Reservation> _Reservations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StatusType> StatusTypes
        {
            get
            {
                if ((_StatusTypes == null))
                {
                    _StatusTypes = base.CreateObjectSet<StatusType>("StatusTypes");
                }
                return _StatusTypes;
            }
        }
        private ObjectSet<StatusType> _StatusTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Admins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdmins(Admin admin)
        {
            base.AddObject("Admins", admin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Computers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComputers(Computer computer)
        {
            base.AddObject("Computers", computer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Genders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGenders(Gender gender)
        {
            base.AddObject("Genders", gender);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Laboratories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLaboratories(Laboratory laboratory)
        {
            base.AddObject("Laboratories", laboratory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProgramCourses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProgramCourses(ProgramCourse programCourse)
        {
            base.AddObject("ProgramCourses", programCourse);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reservations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReservations(Reservation reservation)
        {
            base.AddObject("Reservations", reservation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StatusTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatusTypes(StatusType statusType)
        {
            base.AddObject("StatusTypes", statusType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="Admin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Admin object.
        /// </summary>
        /// <param name="adminId">Initial value of the AdminId property.</param>
        public static Admin CreateAdmin(global::System.Int32 adminId)
        {
            Admin admin = new Admin();
            admin.AdminId = adminId;
            return admin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminId
        {
            get
            {
                return _AdminId;
            }
            set
            {
                if (_AdminId != value)
                {
                    OnAdminIdChanging(value);
                    ReportPropertyChanging("AdminId");
                    _AdminId = StructuralObject.SetValidValue(value, "AdminId");
                    ReportPropertyChanged("AdminId");
                    OnAdminIdChanged();
                }
            }
        }
        private global::System.Int32 _AdminId;
        partial void OnAdminIdChanging(global::System.Int32 value);
        partial void OnAdminIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                OnPersonIdChanging(value);
                ReportPropertyChanging("PersonId");
                _PersonId = StructuralObject.SetValidValue(value, "PersonId");
                ReportPropertyChanged("PersonId");
                OnPersonIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PersonId;
        partial void OnPersonIdChanging(Nullable<global::System.Int32> value);
        partial void OnPersonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true, "Username");
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value, "IsActive");
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Admin__PersonId__3C69FB99", "Person")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("CLMSModel.FK__Admin__PersonId__3C69FB99", "Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("CLMSModel.FK__Admin__PersonId__3C69FB99", "Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("CLMSModel.FK__Admin__PersonId__3C69FB99", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("CLMSModel.FK__Admin__PersonId__3C69FB99", "Person", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="Computer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Computer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Computer object.
        /// </summary>
        /// <param name="computerId">Initial value of the ComputerId property.</param>
        public static Computer CreateComputer(global::System.Int32 computerId)
        {
            Computer computer = new Computer();
            computer.ComputerId = computerId;
            return computer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ComputerId
        {
            get
            {
                return _ComputerId;
            }
            set
            {
                if (_ComputerId != value)
                {
                    OnComputerIdChanging(value);
                    ReportPropertyChanging("ComputerId");
                    _ComputerId = StructuralObject.SetValidValue(value, "ComputerId");
                    ReportPropertyChanged("ComputerId");
                    OnComputerIdChanged();
                }
            }
        }
        private global::System.Int32 _ComputerId;
        partial void OnComputerIdChanging(global::System.Int32 value);
        partial void OnComputerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ComputerName
        {
            get
            {
                return _ComputerName;
            }
            set
            {
                OnComputerNameChanging(value);
                ReportPropertyChanging("ComputerName");
                _ComputerName = StructuralObject.SetValidValue(value, true, "ComputerName");
                ReportPropertyChanged("ComputerName");
                OnComputerNameChanged();
            }
        }
        private global::System.String _ComputerName;
        partial void OnComputerNameChanging(global::System.String value);
        partial void OnComputerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ComputerCode
        {
            get
            {
                return _ComputerCode;
            }
            set
            {
                OnComputerCodeChanging(value);
                ReportPropertyChanging("ComputerCode");
                _ComputerCode = StructuralObject.SetValidValue(value, true, "ComputerCode");
                ReportPropertyChanged("ComputerCode");
                OnComputerCodeChanged();
            }
        }
        private global::System.String _ComputerCode;
        partial void OnComputerCodeChanging(global::System.String value);
        partial void OnComputerCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LaboratoryId
        {
            get
            {
                return _LaboratoryId;
            }
            set
            {
                OnLaboratoryIdChanging(value);
                ReportPropertyChanging("LaboratoryId");
                _LaboratoryId = StructuralObject.SetValidValue(value, "LaboratoryId");
                ReportPropertyChanged("LaboratoryId");
                OnLaboratoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LaboratoryId;
        partial void OnLaboratoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnLaboratoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value, "IsActive");
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Computer__Labora__44FF419A", "Laboratory")]
        public Laboratory Laboratory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Laboratory>("CLMSModel.FK__Computer__Labora__44FF419A", "Laboratory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Laboratory>("CLMSModel.FK__Computer__Labora__44FF419A", "Laboratory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Laboratory> LaboratoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Laboratory>("CLMSModel.FK__Computer__Labora__44FF419A", "Laboratory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Laboratory>("CLMSModel.FK__Computer__Labora__44FF419A", "Laboratory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Reservati__Compu__4D94879B", "Reservation")]
        public EntityCollection<Reservation> Reservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("CLMSModel.FK__Reservati__Compu__4D94879B", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("CLMSModel.FK__Reservati__Compu__4D94879B", "Reservation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="Gender")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gender : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Gender object.
        /// </summary>
        /// <param name="genderId">Initial value of the GenderId property.</param>
        public static Gender CreateGender(global::System.Int32 genderId)
        {
            Gender gender = new Gender();
            gender.GenderId = genderId;
            return gender;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenderId
        {
            get
            {
                return _GenderId;
            }
            set
            {
                if (_GenderId != value)
                {
                    OnGenderIdChanging(value);
                    ReportPropertyChanging("GenderId");
                    _GenderId = StructuralObject.SetValidValue(value, "GenderId");
                    ReportPropertyChanged("GenderId");
                    OnGenderIdChanged();
                }
            }
        }
        private global::System.Int32 _GenderId;
        partial void OnGenderIdChanging(global::System.Int32 value);
        partial void OnGenderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GenderName
        {
            get
            {
                return _GenderName;
            }
            set
            {
                OnGenderNameChanging(value);
                ReportPropertyChanging("GenderName");
                _GenderName = StructuralObject.SetValidValue(value, true, "GenderName");
                ReportPropertyChanged("GenderName");
                OnGenderNameChanged();
            }
        }
        private global::System.String _GenderName;
        partial void OnGenderNameChanging(global::System.String value);
        partial void OnGenderNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK_Gender", "Person")]
        public EntityCollection<Person> People
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Person>("CLMSModel.FK_Gender", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Person>("CLMSModel.FK_Gender", "Person", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="Laboratory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Laboratory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Laboratory object.
        /// </summary>
        /// <param name="laboratoryId">Initial value of the LaboratoryId property.</param>
        public static Laboratory CreateLaboratory(global::System.Int32 laboratoryId)
        {
            Laboratory laboratory = new Laboratory();
            laboratory.LaboratoryId = laboratoryId;
            return laboratory;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LaboratoryId
        {
            get
            {
                return _LaboratoryId;
            }
            set
            {
                if (_LaboratoryId != value)
                {
                    OnLaboratoryIdChanging(value);
                    ReportPropertyChanging("LaboratoryId");
                    _LaboratoryId = StructuralObject.SetValidValue(value, "LaboratoryId");
                    ReportPropertyChanged("LaboratoryId");
                    OnLaboratoryIdChanged();
                }
            }
        }
        private global::System.Int32 _LaboratoryId;
        partial void OnLaboratoryIdChanging(global::System.Int32 value);
        partial void OnLaboratoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LaboratoryName
        {
            get
            {
                return _LaboratoryName;
            }
            set
            {
                OnLaboratoryNameChanging(value);
                ReportPropertyChanging("LaboratoryName");
                _LaboratoryName = StructuralObject.SetValidValue(value, true, "LaboratoryName");
                ReportPropertyChanged("LaboratoryName");
                OnLaboratoryNameChanged();
            }
        }
        private global::System.String _LaboratoryName;
        partial void OnLaboratoryNameChanging(global::System.String value);
        partial void OnLaboratoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LaboratoryCode
        {
            get
            {
                return _LaboratoryCode;
            }
            set
            {
                OnLaboratoryCodeChanging(value);
                ReportPropertyChanging("LaboratoryCode");
                _LaboratoryCode = StructuralObject.SetValidValue(value, true, "LaboratoryCode");
                ReportPropertyChanged("LaboratoryCode");
                OnLaboratoryCodeChanged();
            }
        }
        private global::System.String _LaboratoryCode;
        partial void OnLaboratoryCodeChanging(global::System.String value);
        partial void OnLaboratoryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value, "IsActive");
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Computer__Labora__44FF419A", "Computer")]
        public EntityCollection<Computer> Computers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Computer>("CLMSModel.FK__Computer__Labora__44FF419A", "Computer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Computer>("CLMSModel.FK__Computer__Labora__44FF419A", "Computer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Reservati__Labor__4CA06362", "Reservation")]
        public EntityCollection<Reservation> Reservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("CLMSModel.FK__Reservati__Labor__4CA06362", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("CLMSModel.FK__Reservati__Labor__4CA06362", "Reservation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="personId">Initial value of the PersonId property.</param>
        public static Person CreatePerson(global::System.Int32 personId)
        {
            Person person = new Person();
            person.PersonId = personId;
            return person;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                if (_PersonId != value)
                {
                    OnPersonIdChanging(value);
                    ReportPropertyChanging("PersonId");
                    _PersonId = StructuralObject.SetValidValue(value, "PersonId");
                    ReportPropertyChanged("PersonId");
                    OnPersonIdChanged();
                }
            }
        }
        private global::System.Int32 _PersonId;
        partial void OnPersonIdChanging(global::System.Int32 value);
        partial void OnPersonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lastname
        {
            get
            {
                return _Lastname;
            }
            set
            {
                OnLastnameChanging(value);
                ReportPropertyChanging("Lastname");
                _Lastname = StructuralObject.SetValidValue(value, true, "Lastname");
                ReportPropertyChanged("Lastname");
                OnLastnameChanged();
            }
        }
        private global::System.String _Lastname;
        partial void OnLastnameChanging(global::System.String value);
        partial void OnLastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Firstname
        {
            get
            {
                return _Firstname;
            }
            set
            {
                OnFirstnameChanging(value);
                ReportPropertyChanging("Firstname");
                _Firstname = StructuralObject.SetValidValue(value, true, "Firstname");
                ReportPropertyChanged("Firstname");
                OnFirstnameChanged();
            }
        }
        private global::System.String _Firstname;
        partial void OnFirstnameChanging(global::System.String value);
        partial void OnFirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Middlename
        {
            get
            {
                return _Middlename;
            }
            set
            {
                OnMiddlenameChanging(value);
                ReportPropertyChanging("Middlename");
                _Middlename = StructuralObject.SetValidValue(value, true, "Middlename");
                ReportPropertyChanged("Middlename");
                OnMiddlenameChanged();
            }
        }
        private global::System.String _Middlename;
        partial void OnMiddlenameChanging(global::System.String value);
        partial void OnMiddlenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthdate
        {
            get
            {
                return _Birthdate;
            }
            set
            {
                OnBirthdateChanging(value);
                ReportPropertyChanging("Birthdate");
                _Birthdate = StructuralObject.SetValidValue(value, "Birthdate");
                ReportPropertyChanged("Birthdate");
                OnBirthdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthdate;
        partial void OnBirthdateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GenderId
        {
            get
            {
                return _GenderId;
            }
            set
            {
                OnGenderIdChanging(value);
                ReportPropertyChanging("GenderId");
                _GenderId = StructuralObject.SetValidValue(value, "GenderId");
                ReportPropertyChanged("GenderId");
                OnGenderIdChanged();
            }
        }
        private Nullable<global::System.Int32> _GenderId;
        partial void OnGenderIdChanging(Nullable<global::System.Int32> value);
        partial void OnGenderIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Admin__PersonId__3C69FB99", "Admin")]
        public EntityCollection<Admin> Admins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Admin>("CLMSModel.FK__Admin__PersonId__3C69FB99", "Admin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Admin>("CLMSModel.FK__Admin__PersonId__3C69FB99", "Admin", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK_Gender", "Gender")]
        public Gender Gender
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gender>("CLMSModel.FK_Gender", "Gender").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gender>("CLMSModel.FK_Gender", "Gender").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Gender> GenderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gender>("CLMSModel.FK_Gender", "Gender");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Gender>("CLMSModel.FK_Gender", "Gender", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Student__PersonI__403A8C7D", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("CLMSModel.FK__Student__PersonI__403A8C7D", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("CLMSModel.FK__Student__PersonI__403A8C7D", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="ProgramCourse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProgramCourse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProgramCourse object.
        /// </summary>
        /// <param name="programCourseId">Initial value of the ProgramCourseId property.</param>
        public static ProgramCourse CreateProgramCourse(global::System.Int32 programCourseId)
        {
            ProgramCourse programCourse = new ProgramCourse();
            programCourse.ProgramCourseId = programCourseId;
            return programCourse;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProgramCourseId
        {
            get
            {
                return _ProgramCourseId;
            }
            set
            {
                if (_ProgramCourseId != value)
                {
                    OnProgramCourseIdChanging(value);
                    ReportPropertyChanging("ProgramCourseId");
                    _ProgramCourseId = StructuralObject.SetValidValue(value, "ProgramCourseId");
                    ReportPropertyChanged("ProgramCourseId");
                    OnProgramCourseIdChanged();
                }
            }
        }
        private global::System.Int32 _ProgramCourseId;
        partial void OnProgramCourseIdChanging(global::System.Int32 value);
        partial void OnProgramCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProgramCourseName
        {
            get
            {
                return _ProgramCourseName;
            }
            set
            {
                OnProgramCourseNameChanging(value);
                ReportPropertyChanging("ProgramCourseName");
                _ProgramCourseName = StructuralObject.SetValidValue(value, true, "ProgramCourseName");
                ReportPropertyChanged("ProgramCourseName");
                OnProgramCourseNameChanged();
            }
        }
        private global::System.String _ProgramCourseName;
        partial void OnProgramCourseNameChanging(global::System.String value);
        partial void OnProgramCourseNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProgramCourseCode
        {
            get
            {
                return _ProgramCourseCode;
            }
            set
            {
                OnProgramCourseCodeChanging(value);
                ReportPropertyChanging("ProgramCourseCode");
                _ProgramCourseCode = StructuralObject.SetValidValue(value, true, "ProgramCourseCode");
                ReportPropertyChanged("ProgramCourseCode");
                OnProgramCourseCodeChanged();
            }
        }
        private global::System.String _ProgramCourseCode;
        partial void OnProgramCourseCodeChanging(global::System.String value);
        partial void OnProgramCourseCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value, "IsActive");
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Student__Program__0E6E26BF", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("CLMSModel.FK__Student__Program__0E6E26BF", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("CLMSModel.FK__Student__Program__0E6E26BF", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="Reservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reservation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reservation object.
        /// </summary>
        /// <param name="reservationId">Initial value of the ReservationId property.</param>
        public static Reservation CreateReservation(global::System.Int32 reservationId)
        {
            Reservation reservation = new Reservation();
            reservation.ReservationId = reservationId;
            return reservation;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReservationId
        {
            get
            {
                return _ReservationId;
            }
            set
            {
                if (_ReservationId != value)
                {
                    OnReservationIdChanging(value);
                    ReportPropertyChanging("ReservationId");
                    _ReservationId = StructuralObject.SetValidValue(value, "ReservationId");
                    ReportPropertyChanged("ReservationId");
                    OnReservationIdChanged();
                }
            }
        }
        private global::System.Int32 _ReservationId;
        partial void OnReservationIdChanging(global::System.Int32 value);
        partial void OnReservationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                OnStudentIdChanging(value);
                ReportPropertyChanging("StudentId");
                _StudentId = StructuralObject.SetValidValue(value, "StudentId");
                ReportPropertyChanged("StudentId");
                OnStudentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _StudentId;
        partial void OnStudentIdChanging(Nullable<global::System.Int32> value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LaboratoryId
        {
            get
            {
                return _LaboratoryId;
            }
            set
            {
                OnLaboratoryIdChanging(value);
                ReportPropertyChanging("LaboratoryId");
                _LaboratoryId = StructuralObject.SetValidValue(value, "LaboratoryId");
                ReportPropertyChanged("LaboratoryId");
                OnLaboratoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LaboratoryId;
        partial void OnLaboratoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnLaboratoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ComputerId
        {
            get
            {
                return _ComputerId;
            }
            set
            {
                OnComputerIdChanging(value);
                ReportPropertyChanging("ComputerId");
                _ComputerId = StructuralObject.SetValidValue(value, "ComputerId");
                ReportPropertyChanged("ComputerId");
                OnComputerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ComputerId;
        partial void OnComputerIdChanging(Nullable<global::System.Int32> value);
        partial void OnComputerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TermId
        {
            get
            {
                return _TermId;
            }
            set
            {
                OnTermIdChanging(value);
                ReportPropertyChanging("TermId");
                _TermId = StructuralObject.SetValidValue(value, "TermId");
                ReportPropertyChanged("TermId");
                OnTermIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TermId;
        partial void OnTermIdChanging(Nullable<global::System.Int32> value);
        partial void OnTermIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StatusTypeId
        {
            get
            {
                return _StatusTypeId;
            }
            set
            {
                OnStatusTypeIdChanging(value);
                ReportPropertyChanging("StatusTypeId");
                _StatusTypeId = StructuralObject.SetValidValue(value, "StatusTypeId");
                ReportPropertyChanged("StatusTypeId");
                OnStatusTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _StatusTypeId;
        partial void OnStatusTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnStatusTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateStart
        {
            get
            {
                return _DateStart;
            }
            set
            {
                OnDateStartChanging(value);
                ReportPropertyChanging("DateStart");
                _DateStart = StructuralObject.SetValidValue(value, "DateStart");
                ReportPropertyChanged("DateStart");
                OnDateStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateStart;
        partial void OnDateStartChanging(Nullable<global::System.DateTime> value);
        partial void OnDateStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateEnd
        {
            get
            {
                return _DateEnd;
            }
            set
            {
                OnDateEndChanging(value);
                ReportPropertyChanging("DateEnd");
                _DateEnd = StructuralObject.SetValidValue(value, "DateEnd");
                ReportPropertyChanged("DateEnd");
                OnDateEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateEnd;
        partial void OnDateEndChanging(Nullable<global::System.DateTime> value);
        partial void OnDateEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> TimeConsumed
        {
            get
            {
                return _TimeConsumed;
            }
            set
            {
                OnTimeConsumedChanging(value);
                ReportPropertyChanging("TimeConsumed");
                _TimeConsumed = StructuralObject.SetValidValue(value, "TimeConsumed");
                ReportPropertyChanged("TimeConsumed");
                OnTimeConsumedChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _TimeConsumed;
        partial void OnTimeConsumedChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTimeConsumedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Reservati__Compu__4D94879B", "Computer")]
        public Computer Computer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("CLMSModel.FK__Reservati__Compu__4D94879B", "Computer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("CLMSModel.FK__Reservati__Compu__4D94879B", "Computer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Computer> ComputerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("CLMSModel.FK__Reservati__Compu__4D94879B", "Computer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Computer>("CLMSModel.FK__Reservati__Compu__4D94879B", "Computer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Reservati__Labor__4CA06362", "Laboratory")]
        public Laboratory Laboratory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Laboratory>("CLMSModel.FK__Reservati__Labor__4CA06362", "Laboratory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Laboratory>("CLMSModel.FK__Reservati__Labor__4CA06362", "Laboratory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Laboratory> LaboratoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Laboratory>("CLMSModel.FK__Reservati__Labor__4CA06362", "Laboratory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Laboratory>("CLMSModel.FK__Reservati__Labor__4CA06362", "Laboratory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Reservati__Statu__4F7CD00D", "StatusType")]
        public StatusType StatusType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StatusType>("CLMSModel.FK__Reservati__Statu__4F7CD00D", "StatusType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StatusType>("CLMSModel.FK__Reservati__Statu__4F7CD00D", "StatusType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StatusType> StatusTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StatusType>("CLMSModel.FK__Reservati__Statu__4F7CD00D", "StatusType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StatusType>("CLMSModel.FK__Reservati__Statu__4F7CD00D", "StatusType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Reservati__Stude__4BAC3F29", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("CLMSModel.FK__Reservati__Stude__4BAC3F29", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("CLMSModel.FK__Reservati__Stude__4BAC3F29", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("CLMSModel.FK__Reservati__Stude__4BAC3F29", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("CLMSModel.FK__Reservati__Stude__4BAC3F29", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="StatusType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StatusType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StatusType object.
        /// </summary>
        /// <param name="statusTypeId">Initial value of the StatusTypeId property.</param>
        public static StatusType CreateStatusType(global::System.Int32 statusTypeId)
        {
            StatusType statusType = new StatusType();
            statusType.StatusTypeId = statusTypeId;
            return statusType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusTypeId
        {
            get
            {
                return _StatusTypeId;
            }
            set
            {
                if (_StatusTypeId != value)
                {
                    OnStatusTypeIdChanging(value);
                    ReportPropertyChanging("StatusTypeId");
                    _StatusTypeId = StructuralObject.SetValidValue(value, "StatusTypeId");
                    ReportPropertyChanged("StatusTypeId");
                    OnStatusTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _StatusTypeId;
        partial void OnStatusTypeIdChanging(global::System.Int32 value);
        partial void OnStatusTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusTypeName
        {
            get
            {
                return _StatusTypeName;
            }
            set
            {
                OnStatusTypeNameChanging(value);
                ReportPropertyChanging("StatusTypeName");
                _StatusTypeName = StructuralObject.SetValidValue(value, true, "StatusTypeName");
                ReportPropertyChanged("StatusTypeName");
                OnStatusTypeNameChanged();
            }
        }
        private global::System.String _StatusTypeName;
        partial void OnStatusTypeNameChanging(global::System.String value);
        partial void OnStatusTypeNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Reservati__Statu__4F7CD00D", "Reservation")]
        public EntityCollection<Reservation> Reservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("CLMSModel.FK__Reservati__Statu__4F7CD00D", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("CLMSModel.FK__Reservati__Statu__4F7CD00D", "Reservation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        public static Student CreateStudent(global::System.Int32 studentId)
        {
            Student student = new Student();
            student.StudentId = studentId;
            return student;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                if (_StudentId != value)
                {
                    OnStudentIdChanging(value);
                    ReportPropertyChanging("StudentId");
                    _StudentId = StructuralObject.SetValidValue(value, "StudentId");
                    ReportPropertyChanged("StudentId");
                    OnStudentIdChanged();
                }
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                OnPersonIdChanging(value);
                ReportPropertyChanging("PersonId");
                _PersonId = StructuralObject.SetValidValue(value, "PersonId");
                ReportPropertyChanged("PersonId");
                OnPersonIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PersonId;
        partial void OnPersonIdChanging(Nullable<global::System.Int32> value);
        partial void OnPersonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentNo
        {
            get
            {
                return _StudentNo;
            }
            set
            {
                OnStudentNoChanging(value);
                ReportPropertyChanging("StudentNo");
                _StudentNo = StructuralObject.SetValidValue(value, true, "StudentNo");
                ReportPropertyChanged("StudentNo");
                OnStudentNoChanged();
            }
        }
        private global::System.String _StudentNo;
        partial void OnStudentNoChanging(global::System.String value);
        partial void OnStudentNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramCourseId
        {
            get
            {
                return _ProgramCourseId;
            }
            set
            {
                OnProgramCourseIdChanging(value);
                ReportPropertyChanging("ProgramCourseId");
                _ProgramCourseId = StructuralObject.SetValidValue(value, "ProgramCourseId");
                ReportPropertyChanged("ProgramCourseId");
                OnProgramCourseIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramCourseId;
        partial void OnProgramCourseIdChanging(Nullable<global::System.Int32> value);
        partial void OnProgramCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> TimeAllocated
        {
            get
            {
                return _TimeAllocated;
            }
            set
            {
                OnTimeAllocatedChanging(value);
                ReportPropertyChanging("TimeAllocated");
                _TimeAllocated = StructuralObject.SetValidValue(value, "TimeAllocated");
                ReportPropertyChanged("TimeAllocated");
                OnTimeAllocatedChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _TimeAllocated;
        partial void OnTimeAllocatedChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTimeAllocatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Student__PersonI__403A8C7D", "Person")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("CLMSModel.FK__Student__PersonI__403A8C7D", "Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("CLMSModel.FK__Student__PersonI__403A8C7D", "Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("CLMSModel.FK__Student__PersonI__403A8C7D", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("CLMSModel.FK__Student__PersonI__403A8C7D", "Person", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Student__Program__0E6E26BF", "ProgramCourse")]
        public ProgramCourse ProgramCourse
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProgramCourse>("CLMSModel.FK__Student__Program__0E6E26BF", "ProgramCourse").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProgramCourse>("CLMSModel.FK__Student__Program__0E6E26BF", "ProgramCourse").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProgramCourse> ProgramCourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProgramCourse>("CLMSModel.FK__Student__Program__0E6E26BF", "ProgramCourse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProgramCourse>("CLMSModel.FK__Student__Program__0E6E26BF", "ProgramCourse", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CLMSModel", "FK__Reservati__Stude__4BAC3F29", "Reservation")]
        public EntityCollection<Reservation> Reservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("CLMSModel.FK__Reservati__Stude__4BAC3F29", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("CLMSModel.FK__Reservati__Stude__4BAC3F29", "Reservation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CLMSModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }

    #endregion

}
